version: '3.8'

services:
  webui:
    image: aihpvideo/hpvideo:test
    container_name: hpvideo-test
    env_file:
      - /data/env/hpvideo/test/.env
    environment:
      - NEST_ORIGIN=http://nest:3008
    ports:
      - '5002:8080'
    networks:
      - degpt-network
    depends_on:
      - nest
    restart: unless-stopped

  nest:
    image: aihpvideo/hpvideo-nest:test
    container_name: hpvideo-nest-test
    networks:
      - degpt-network
    restart: unless-stopped

networks:
  degpt-network:
    external: true
