# Deploy them independently

# SERVER_HOST: The IP address or domain name of your server.
# SERVER_USER: SSH login username.
# SERVER_PASSWORD: SSH login password. (It is recommended to use SSH key pair authentication instead of password)
# DOCKER_PASSWORD
# DOCKER_USERNAME

name: Deploy to Server # Define the name of the workflow

on: # Define the events that trigger the workflow
  push: # When the code is pushed
    branches: # Specify the branches that trigger the workflow
      - main # Only pushes to the main branch will trigger this workflow

jobs: # Define the jobs to be executed
  # timeout-minutes: 30
  build: # Job identifier, here is the build job
    runs-on: ubuntu-latest # Specify the running environment as the latest version of the Ubuntu virtual environment
    steps: # Define the steps to be executed
      - name: Checkout code # Step name
        uses: actions/checkout@v2 # Use the official GitHub Action actions/checkout@v2 to check out the repository code

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        # run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 


      - name: Build and Push Docker image # Step name
        uses: docker/build-push-action@v5 # Use docker/build-push-action@v2 to build and push the Docker image
        with: # Parameters passed to the action
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}

          push: true # Push the image to Docker Hub
          tags: aihpvideo/hpvideo:prod # Set the tag of the image
